
spring:
  #Database properties!
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/main_db
    username: main_user
    password: main_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  #Email properties
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 25
    username: f45b9ad5a0312f
    password: 05299375945167
    protocol: smtp
