spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:main_db}
    username: ${DB_USER:main_user}
    password: ${DB_PASS:main_pass}
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
